name: CI

on: [push]

jobs:
  build:
    name: Elixir ${{matrix.elixir}} (Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['25.3', '26.0']
        elixir: ['1.13.4', '1.14.4', '1.15.2']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix deps.unlock --unused
      - run: mix credo --strict
      - name: "Check formatted?"
        run: mix format mix.exs "examples/*.exs" "lib/**/*.{ex,exs}" "test/**/*.exs" --check-formatted
        if: ${{ startsWith(matrix.elixir, '1.14') }}
      - run: mix test